global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus'
  - job_name: 'alpha1-apps'
    metrics_path: '/api/metrics'
    static_configs:
      - targets:
          ['alpha.simpfi.ai']
        labels:
          environment: 'alpha1'
